export enum Conference {
    East = 'East',
    West = 'West',
    South = 'South',
    Midwest = 'Midwest'
}

export enum Team {
    AbileneChristian = 'Abilene Christian',
    Alabama = 'Alabama',
    AppalachianState = 'Appalachian State',
    Arkansas = 'Arkansas',
    Baylor = 'Baylor',
    BYU = 'BYU',
    ClevelandState = 'Cleveland State',
    Clemson = 'Clemson',
    Colorado = 'Colorado',
    Creighton = 'Creighton',
    Drake = 'Drake',
    Drexel = 'Drexel',
    EasternWashington = 'Eastern Washington',
    FloridaState = 'Florida State',
    GeorgiaTech = 'Georgia Tech',
    Gonzaga = 'Gonzaga',
    GrandCanyon = 'Grand Canyon',
    Hartford = 'Hartford',
    Houston = 'Houston',
    Illinois = 'Illinois',
    Iona = 'Iona',
    Iowa = 'Iowa',
    Kansas = 'Kansas',
    Liberty = 'Liberty',
    LoyolaChicago = 'Loyola Chicago',
    LSU = 'LSU',
    Maryland = 'Maryland',
    Michigan = 'Michigan',
    MoreheadState = 'Morehead State',
    MountStMarys = 'Mount St. Mary\'s',
    NorfolkState = 'Norfolk State',
    NorthCarolina = 'North Carolina',
    OhioState = 'Ohio State',
    Oklahoma = 'Oklahoma',
    OklahomaState = 'Oklahoma State',
    OralRoberts = 'Oral Roberts',
    Oregon = 'Oregon',
    Purdue = 'Purdue',
    Rutgers = 'Rutgers',
    SanDiegoState = 'San Diego State',
    StBonaventure = 'St. Bonaventure',
    Syracuse = 'Syracuse',
    Tennessee = 'Tennessee',
    Texas = 'Texas',
    TexasTech = 'Texas Tech',
    UConn = 'UConn',
    UCSB = 'UCSB',
    USC = 'USC',
    VCU = 'VCU',
    Virginia = 'Virginia',
    Winthrop = 'Winthrop',
    Wisconsin = 'Wisconsin'
}

export interface TeamSimulationInfo {
    conference: Conference;
    team: Team;
    seed: number;
    elo: number;
    eliminated: boolean;
}

export const initialTeams: TeamSimulationInfo[] = [
    { conference: Conference.East, team: Team.Michigan, seed: 1, elo: 2000, eliminated: false },
    { conference: Conference.East, team: Team.LSU, seed: 2, elo: 1900, eliminated: false },
    { conference: Conference.East, team: Team.Colorado, seed: 3, elo: 1800, eliminated: false },
    { conference: Conference.East, team: Team.FloridaState, seed: 4, elo: 1700, eliminated: false },
    { conference: Conference.East, team: Team.GeorgiaTech, seed: 5, elo: 1600, eliminated: false },
    { conference: Conference.East, team: Team.BYU, seed: 6, elo: 1500, eliminated: false },
    { conference: Conference.East, team: Team.Clemson, seed: 7, elo: 1400, eliminated: false },
    { conference: Conference.East, team: Team.UConn, seed: 8, elo: 1300, eliminated: false },
    { conference: Conference.East, team: Team.LoyolaChicago, seed: 9, elo: 1200, eliminated: false },
    { conference: Conference.East, team: Team.NorthCarolina, seed: 10, elo: 1100, eliminated: false },
    { conference: Conference.East, team: Team.Rutgers, seed: 11, elo: 1000, eliminated: false },
    { conference: Conference.East, team: Team.StBonaventure, seed: 12, elo: 900, eliminated: false },
    { conference: Conference.East, team: Team.Syracuse, seed: 13, elo: 800, eliminated: false },
    { conference: Conference.East, team: Team.Maryland, seed: 14, elo: 700, eliminated: false },
    { conference: Conference.East, team: Team.VCU, seed: 15, elo: 600, eliminated: false },
    { conference: Conference.East, team: Team.Drake, seed: 16, elo: 500, eliminated: false },
    { conference: Conference.West, team: Team.Gonzaga, seed: 1, elo: 2000, eliminated: false },
    { conference: Conference.West, team: Team.Baylor, seed: 2, elo: 1900, eliminated: false },
    { conference: Conference.West, team: Team.Iowa, seed: 3, elo: 1800, eliminated: false },
    { conference: Conference.West, team: Team.Kansas, seed: 4, elo: 1700, eliminated: false },
    { conference: Conference.West, team: Team.Arkansas, seed: 5, elo: 1600, eliminated: false },
    { conference: Conference.West, team: Team.Texas, seed: 6, elo: 1500, eliminated: false },
    { conference: Conference.West, team: Team.OklahomaState, seed: 7, elo: 1400, eliminated: false },
    { conference: Conference.West, team: Team.Purdue, seed: 8, elo: 1300, eliminated: false },
    { conference: Conference.West, team: Team.TexasTech, seed: 9, elo: 1200, eliminated: false },
    { conference: Conference.West, team: Team.Virginia, seed: 10, elo: 1100, eliminated: false },
    { conference: Conference.West, team: Team.Creighton, seed: 11, elo: 1000, eliminated: false },
    { conference: Conference.West, team: Team.Colorado, seed: 12, elo: 900, eliminated: false },
    { conference: Conference.West, team: Team.USC, seed: 13, elo: 800, eliminated: false },
    { conference: Conference.West, team: Team.BYU, seed: 14, elo: 700, eliminated: false },
    { conference: Conference.West, team: Team.Tennessee, seed: 15, elo: 600, eliminated: false },
    { conference: Conference.West, team: Team.Wisconsin, seed: 16, elo: 500, eliminated: false },
    { conference: Conference.South, team: Team.Houston, seed: 1, elo: 2000, eliminated: false },
    { conference: Conference.South, team: Team.Illinois, seed: 2, elo: 1900, eliminated: false },
    { conference: Conference.South, team: Team.OhioState, seed: 3, elo: 1800, eliminated: false },
    { conference: Conference.South, team: Team.FloridaState, seed: 4, elo: 1700, eliminated: false },
    { conference: Conference.South, team: Team.Kansas, seed: 5, elo: 1600, eliminated: false },
    { conference: Conference.South, team: Team.Arkansas, seed: 6, elo: 1500, eliminated: false },
    { conference: Conference.South, team: Team.Texas, seed: 7, elo: 1400, eliminated: false },
    { conference: Conference.South, team: Team.OklahomaState, seed: 8, elo: 1300, eliminated: false },
    { conference: Conference.South, team: Team.Purdue, seed: 9, elo: 1200, eliminated: false },
    { conference: Conference.South, team: Team.TexasTech, seed: 10, elo: 1100, eliminated: false },
    { conference: Conference.South, team: Team.Virginia, seed: 11, elo: 1000, eliminated: false },
    { conference: Conference.South, team: Team.Creighton, seed: 12, elo: 900, eliminated: false },
    { conference: Conference.South, team: Team.Colorado, seed: 13, elo: 800, eliminated: false },
    { conference: Conference.South, team: Team.USC, seed: 14, elo: 700, eliminated: false },
    { conference: Conference.South, team: Team.BYU, seed: 15, elo: 600, eliminated: false },
    { conference: Conference.South, team: Team.Tennessee, seed: 16, elo: 500, eliminated: false },
    { conference: Conference.Midwest, team: Team.Gonzaga, seed: 1, elo: 2000, eliminated: false },
    { conference: Conference.Midwest, team: Team.Baylor, seed: 2, elo: 1900, eliminated: false },
    { conference: Conference.Midwest, team: Team.Iowa, seed: 3, elo: 1800, eliminated: false },
    { conference: Conference.Midwest, team: Team.Kansas, seed: 4, elo: 1700, eliminated: false },
    { conference: Conference.Midwest, team: Team.Arkansas, seed: 5, elo: 1600, eliminated: false },
    { conference: Conference.Midwest, team: Team.Texas, seed: 6, elo: 1500, eliminated: false },
    { conference: Conference.Midwest, team: Team.OklahomaState, seed: 7, elo: 1400, eliminated: false },
    { conference: Conference.Midwest, team: Team.Purdue, seed: 8, elo: 1300, eliminated: false },
    { conference: Conference.Midwest, team: Team.TexasTech, seed: 9, elo: 1200, eliminated: false },
    { conference: Conference.Midwest, team: Team.Virginia, seed: 10, elo: 1100, eliminated: false },
    { conference: Conference.Midwest, team: Team.Creighton, seed: 11, elo: 1000, eliminated: false },
    { conference: Conference.Midwest, team: Team.Colorado, seed: 12, elo: 900, eliminated: false },
    { conference: Conference.Midwest, team: Team.USC, seed: 13, elo: 800, eliminated: false },
    { conference: Conference.Midwest, team: Team.BYU, seed: 14, elo: 700, eliminated: false },
    { conference: Conference.Midwest, team: Team.Tennessee, seed: 15, elo: 600, eliminated: false },
    { conference: Conference.Midwest, team: Team.Wisconsin, seed: 16, elo: 500, eliminated: false }
];